sudo: required
services:
   -docker
   
   before_install:
     - docker build -t dimplewraich/flutter-cloud-app-f Dockerfile.dev .
     
     script:
       - docker run -e CI=true dimplewraich/flutter-cloud-app npm run test
